#!/usr/bin/env bash

repo_index=${1}

curl -f -H 'Cache-Control: max-age=0,no-cache' -H 'Host: releases.rancher.com' "https://c.storage.googleapis.com/server-charts/${repo_index}/index.yaml?$(date +%s%N)" -o /tmp/index.yaml

helm repo index --merge /tmp/index.yaml ./charts/${repo_index}
