#!/usr/bin/env bash

cd $(dirname $0)/..

# Check for helm
hash helm >/dev/null 2>&1
if [[ $? > 0 ]]; then
    echo "helm not found. Helm is required to run tests."
    exit 1
fi

helm lint ./rancher
