apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "rancher.fullname" . }}

{{- if .Values.nodeport }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}-nodport
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 443
    nodePort: {{ .Values.nodeport }}
    protocol: TCP
    name: https
  selector:
    app: {{ template "rancher.fullname" . }}
{{- end }}
